## Docker Testing

version: "3.7"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log/mosquitto.log
  
  mqtt-client:
    image: emqx/mqttx-web 
    container_name: mqtt-client
    ports:
      - "9000:80"

  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  

volumes:
  config:
  data:
  log:
  db:

networks:
  default:
    name: mqtt
    external: true